{{- if and .Values.persistence.worker.enabled .Values.nfsServer }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "erpnext.fullname" . }}-nfs
  labels:
    {{- include "erpnext.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "erpnext.name" . }}-nfs
      app.kubernetes.io/instance: {{ .Release.Name }}-nfs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "erpnext.name" . }}-nfs
        app.kubernetes.io/instance: {{ .Release.Name }}-nfs
    spec:
      containers:
      - name: nfs-server
        image: erichough/nfs-server:2.2.1
        ports:
          - name: nfs
            containerPort: 2049
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs-pvc
        env:
          - name: NFS_EXPORT_0
            value: "/exports *(rw,sync,nohide)"
        securityContext:
          capabilities:
            add:
              - SYS_ADMIN
      volumes:
        - name: nfs-pvc
          persistentVolumeClaim:
            claimName: {{ template "erpnext.fullname" . }}-nfs
{{- end }}