{{- if and .Values.persistence.worker.enabled .Values.nfsServer }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "erpnext.fullname" . }}-nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
{{- end }}